[package]
name = "roar"
version = "0.1.0"
authors = ["miyamoen <akihito.biblioteca@gmail.com>"]

[dependencies]
reqwest = "0.8"
clap = "2.30"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
console = "0.6"
indicatif = "0.9"
dialoguer = "0.1"
serde_json = "1.0.10"
